version: '3.8'

services:
  # Base de données PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: ecole_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecole_privee
      POSTGRES_USER: ecole_user
      POSTGRES_PASSWORD: ecole_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - ecole_network

  # Application Next.js
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecole_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://ecole_user:ecole_password@postgres:5432/ecole_privee
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=fnfT1mQ2dWCmwv3ac62Tr1BTmGCvQ4aN
    depends_on:
      - postgres
    networks:
      - ecole_network
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres_data:

networks:
  ecole_network:
    driver: bridge
